// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtLSS8AjDMMjhkE6beOdc0LKY6Q77QekI',
    appId: '1:889669246831:web:935cf0af65ed65d01bd29a',
    messagingSenderId: '889669246831',
    projectId: 'wechat-a4729',
    authDomain: 'wechat-a4729.firebaseapp.com',
    storageBucket: 'wechat-a4729.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeVjDczqrF--Ld62OUKffMYKc0I1OyCc',
    appId: '1:889669246831:android:6bceb97771392c7e1bd29a',
    messagingSenderId: '889669246831',
    projectId: 'wechat-a4729',
    storageBucket: 'wechat-a4729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHhhuBpDgTZbJgyzW5Vuf5pCq5NaT0GCA',
    appId: '1:889669246831:ios:21a4150697ae57361bd29a',
    messagingSenderId: '889669246831',
    projectId: 'wechat-a4729',
    storageBucket: 'wechat-a4729.appspot.com',
    androidClientId: '889669246831-j2gsdp6u8390hgdksb3hdno440dpop5j.apps.googleusercontent.com',
    iosClientId: '889669246831-n55rk7fb6cl92fdnchtplrgqvlmlh667.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHhhuBpDgTZbJgyzW5Vuf5pCq5NaT0GCA',
    appId: '1:889669246831:ios:21a4150697ae57361bd29a',
    messagingSenderId: '889669246831',
    projectId: 'wechat-a4729',
    storageBucket: 'wechat-a4729.appspot.com',
    androidClientId: '889669246831-j2gsdp6u8390hgdksb3hdno440dpop5j.apps.googleusercontent.com',
    iosClientId: '889669246831-n55rk7fb6cl92fdnchtplrgqvlmlh667.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtLSS8AjDMMjhkE6beOdc0LKY6Q77QekI',
    appId: '1:889669246831:web:8b39b0044cd4ece91bd29a',
    messagingSenderId: '889669246831',
    projectId: 'wechat-a4729',
    authDomain: 'wechat-a4729.firebaseapp.com',
    storageBucket: 'wechat-a4729.appspot.com',
  );

}